#page title
page_title                                : Filler App                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1234793120                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://tailwindflex.com/public/images/thumbnails/simple-coming-soon-page-2/canvas.min.webp?v=1                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://tailwindflex.com/public/images/thumbnails/simple-coming-soon-page-2/canvas.min.webp?v=1                                          # Enter Google Play Store URL.
presskit_download_link                    : https://otechgroup.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

# app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_icon                                  : assets/filler_logo_small.jpg                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Filler Gas App                                         # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : <b>Filler - Fuel Delivered on Demand</b>
                                            <br>Skip the gas station with Filler. Just tap the app, set your location and time, and we'll bring the fuel to you. Simple, convenient, and ready when you are.
enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : OtechGroup                               
your_link                                 : https://otechgroup.com                     
your_city                                 : New York                                
email_address                             : help.otechgroup@gmail.com
facebook_username                         : otechgroup                                           
instagram_username                        : otechgroup
twitter_username                          : otechgroup
github_username                           : otechgroup
youtube_username                          : otechgroup
mastodon_link                             : https://mastodon.social/@otechgroup



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : On-Demand Fuel Delivery
    description                           : Never run out of gas again! Filler allows you to request fuel delivery to your vehicle's location with just a few taps.
    fontawesome_icon_name                 : gas-pump
  
  - title                                 : Locate Your Vehicle
    description                           : Easily pinpoint your vehicle's location using our built-in GPS tracking system, ensuring accurate fuel delivery every time.
    fontawesome_icon_name                 : location-arrow
  
  - title                                 : Convenient Scheduling
    description                           : Schedule your fuel delivery for a time and place that suits you best, whether it's at home, work, or on the go.
    fontawesome_icon_name                 : calendar-alt
  
  - title                                 : Secure Payment Options
    description                           : Enjoy hassle-free payments through our secure in-app payment system, accepting major credit cards and digital wallets.
    fontawesome_icon_name                 : credit-card
  
  - title                                 : Real-Time Tracking
    description                           : Stay informed with real-time updates on the status of your fuel delivery, from request to arrival.
    fontawesome_icon_name                 : truck
  
  - title                                 : Eco-Friendly Approach
    description                           : Filler's mobile fuel delivery service reduces unnecessary travel and emissions, contributing to a greener environment.
    fontawesome_icon_name                 : leaf
  
  - title                                 : Loyalty Rewards
    description                           : Earn rewards and exclusive discounts for your loyalty to Filler, making every fuel delivery even more rewarding.
    fontawesome_icon_name                 : gift
  
  - title                                 : 24/7 Customer Support
    description                           : Our dedicated customer support team is available around the clock to assist you with any questions or concerns.
    fontawesome_icon_name                 : headset
  
  - title                                 : Personalized Experience
    description                           : Enjoy a tailored experience with customizable preferences, notifications, and personalized recommendations based on your fueling habits.
    fontawesome_icon_name                 : user-cog

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/gas-station.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
